version: '3.8'

services:
  emqx1:
    image: emqx:5.3.0
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io]"
      - "EMQX_NODE__COOKIE=09e45edb-7c92-44da-a682-79f0b76e7ada"
    networks:
      emqx_network:
        aliases:
          - node1.emqx.io
    ports:
      - 18083:18083
    deploy:
      replicas: 1

  emqx2:
    image: emqx:5.3.0
    environment:
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io]"
      - "EMQX_NODE__COOKIE=09e45edb-7c92-44da-a682-79f0b76e7ada"
    networks:
      emqx_network:
    depends_on:
      - emqx1
    deploy:
      replicas: 4

networks:
  emqx_network:
    name: emqx_network
    external: true
